import { expect, test } from '@playwright/test';
import { stableScene } from './helpers';
test('SVG room, mailbox, book, poster, stove, person and station entries activate from the keyboard', async ({ page }) => {
  await stableScene(page);
  const activate = async (selector: string, key = 'Enter') => { await page.locator(selector).focus(); await page.locator(selector).press(key); };
  await activate('#room-my_room');
  await expect(page.locator('#panoramic-world-stage')).toHaveAttribute('data-zoom', '1.55');
  await activate('#room-friend_room', 'Space');
  const person = page.locator('#room-living_nook g[aria-label="查看人物状态"]').first();
  await person.focus(); await person.press('Enter');
  await expect(page.getByRole('heading', { name: '小鱼', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭人物状态', exact: true }).click();
  await activate('#isometric-bookshelf');
  await expect(page.getByText('手作做旧粗原木书架 · 藏书插槽', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭书架', exact: true }).click();
  const book = page.locator('g[aria-label^="检视书籍："]').first();
  await book.focus(); await book.press('Enter');
  await expect(page.getByText('手作做旧粗原木书架 · 藏书插槽', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: '关闭书架', exact: true }).click();
  await page.getByRole('button', { name: '赏析红辣椒海报', exact: true }).focus();
  await page.getByRole('button', { name: '赏析红辣椒海报', exact: true }).press('Enter');
  await expect(page.getByText('《红辣椒》', { exact: true }).last()).toBeVisible();
  await page.getByRole('button', { name: '关闭画作', exact: true }).click();
  const before = await page.evaluate(() => localStorage.getItem('storybook_stove_color'));
  await activate('#stove-scalable-body-group');
  await expect.poll(() => page.evaluate(() => localStorage.getItem('storybook_stove_color'))).not.toBe(before);
  await activate('#room-observatory'); await activate('#alien-receiver-assembly');
  await expect(page.getByText(/SETI 频率/)).toBeVisible();
  await activate('#mailbox-group');
  await expect(page.getByRole('heading', { name: '前廊木信箱', exact: true })).toBeVisible();
});
